version: '3'
services:
  postgres:
    image: postgres:13
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 512M
    ports:
      - "5432:5432"
    volumes:
      - /host/path:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
    ports:
      - "5050:80"
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=myemail
      - PGADMIN_DEFAULT_PASSWORD=mypassword